### ISSUE TITLE
Feature request: support proxying websocket connections

### ISSUE THREAD

**Issue by ghost** [lwsjs/rewrite#7] opened 2019-10-21 03:56 UTC
I would like to proxy websocket connections. I looked at the code and I think it would be possible. Here is some documentation from [https-proxy-agent](https://github.com/TooTallNate/node-https-proxy-agent). I am happy to have a go at implementing this. Would love any guidance or suggestions.

**Comment by 75lb** [comment] 2019-10-22 16:39
Hi, closing this as a duplicate of https://github.com/lwsjs/local-web-server/issues/126.

Yes, feel free to implement it and submit a PR. The PR doesn't need to be perfect, I will take a look and make changes if necessary, thanks.

**Closed as completed by 75lb** 2019-10-22 16:39 UTC
